### PR TITLE
[WIP] more C++ bindings

### PR DESCRIPTION
**Pull request by skimo-openhub**
This extends the C++ bindings with subclasses for isl_schedule_node.

### CODE REVIEW

**Comment by ftynse** [comment]
This exports lists differently that we have already, we probably don't wont to keep both at the same time

**Comment by skimo-openhub** [comment]
On Thu, Dec 07, 2017 at 04:57:13PM +0000, ftynse wrote:
> This exports lists differently that we have already, we probably don't wont to keep both at the same time

The way I export lists here is how I plan to export
them in mainline.  Does it look reasonable?
As to the one that was in place in ntv_dev, I haven't
looked at it in full detail yet, but I think it's best
to keep it until we have migrated completely to
the other one.  That means in particular, that
we first need to decide what to do with isl_id and
we probably want to support range-based for loops
on top of the mainline lists.
Do you see any risk of conflict in the mean time?

skimo

**Comment by tobig** [comment]
The lists look reasonable on a higher level. Alex had some earlier approaches which looked slightly different.

He also had patches for generating iterator based loops: https://github.com/PollyLabs/isl/pull/20/commits/1fa18f61c51ff92a7298111613f21e7a9fc14491

Here some more thoughts about range-based loops: https://github.com/PollyLabs/isl/issues/5

**Comment by ftynse** [comment]
I find the approach we have with templates more idiomatic C++: list is a container with element type as template argument.  What one should do if they want to export a new list now?

We have a minimalistic `id` export here `https://github.com/PollyLabs/isl/pull/21`.  No user pointers to be compatible with Python, the argument being "if you want to access user pointers, you are using isl C way and should use C interface".

We also have a separate patchset for the lists support currently used in ntv_dev in https://github.com/PollyLabs/isl/pull/20/files

**Comment by skimo-openhub** [comment]
On Fri, Dec 08, 2017 at 09:56:49AM +0000, ftynse wrote:
> I find the approach we have with templates more idiomatic C++: list is a container with element type as template argument.  What one should do if they want to export a new list now?

Change ISL_DECLARE_LIST(_*) to ISL_DECLARE_EXPORTED_LIST(_*)

skimo

**Comment by ftynse** [comment]
I meant more generally, with two approaches available, which one should 
be chosen?

**Comment by tobig** [comment]
I think both are reasonable choices. I also have a slight preference to Alex's more idiomatic template approach, but would also be fine with Sven's approach. I am sure Michael and Alex also would have comments. ;-)

**Comment by skimo-openhub** [comment]
On Fri, Dec 08, 2017 at 10:22:43AM +0000, ftynse wrote:
> I meant more generally, with two approaches available, which one should 
> be chosen?

As long as we are in this intermediate state,
I think we should consider this question if and when
it arises.

skimo

**Pull request merged**
