### PR TITLE
rename isl_*_list_get and isl_*_list_n

### PR DESCRIPTION
**Pull request by skimo-openhub**

### CODE REVIEW

**Comment by ftynse** [comment]
Do you prefer `isl_*_list_get_at` to `isl_*_list_at` ?

**Comment by skimo-openhub** [comment]
On Fri, Jun 22, 2018 at 06:45:34AM -0700, ftynse wrote:
> Do you prefer `isl_*_list_get_at` to `isl_*_list_at` ?  

Yes, for the C interface, it helps to know which functions
take their arguments.  (For the C++ interface, the "get_"
prefix should arguably be removed since it is irrelevant,
but we will have to keep the get_ names too for backward
compatibility, at least in the Python interface.)

skimo

**Comment by tobig** [comment]
Nice

**Comment by skimo-openhub** [comment]
On Wed, Jun 27, 2018 at 05:11:27AM -0700, ftynse wrote:
> ftynse approved this pull request.
> 
> Does this mean that plain `_get` and `_n` are not kept as aliases?

There is no need to keep them since they don't exist (in mainline).

skimo

**Comment by tobig** [comment]
Nice.

**Pull request merged**
