### PR TITLE
Reschedule

### PR DESCRIPTION
**Pull request by skimo-openhub**
This adds support for rescheduling a subtree by introducing
a isl_schedule_node_schedule that takes as input the subtree that needs
to be rescheduled and the schedule constraints.

### CODE REVIEW

**Comment by nicolasvasilache** [comment]
@ftynse  @skimo-openhub how should we proceed here?
Should we take this as the source of truth on top of the current ISL master, then merge the ntv_dev diffs into a single one that for which we resolve the conflicts and try to upstream pieces of it?
Another suggestion ?

It seems like resolving all the conflicts by applying this on top of the current ntv_dev is going to be more trouble than it is worth.

**Comment by ftynse** [comment]
Let's discuss this live tomorrow?

**Comment by nicolasvasilache** [comment]
sounds good

**Comment by skimo-openhub** [comment]
I could rebase these changes on top of the merge base (isl-0.18-600-geef53c490), but it's pretty old.
What's the procedure for merging in upstream changes?  It may be best to do that first with the current master.  Then I can rebase this branch on top of that.

**Comment by ftynse** [comment]
There's no procedure for upstream, hence my suggestion to discuss it 
during today's meeting.

I'm pretty sure there are some conflicting changes between the local 
fork and upstream isl.

**Comment by skimo-openhub** [comment]
@ftynse, I tried to resolve the merge conflicts, but I see you introduced a call to
node_extract_schedule, whereas I've replaced node_extract_schedule by
node_extract_band_schedule in my branch.
There is little documentation about the callback, so it's not clear to me,
can your call to node_extract_schedule be replaced by a call to
node_extract_band_schedule as well?

**Comment by ftynse** [comment]
Theoretically, the callback was intended as an additional external heuristic for clustering and, depending on a particular heuristic, may want to see the full schedule rather then the schedule of the current band.

Practically, current heuristics do not use the schedules at all.

The interface has to change anyway, so I'm fine with using `node_extract_band_schedule` for now.

**Comment by nicolasvasilache** [comment]
Makes sense, thanks!

**Pull request merged**
