### PR TITLE
export all lists in the same way

### PR DESCRIPTION
**Pull request by skimo-openhub**

### CODE REVIEW

**Comment by tobig** [comment]
Very nice. Any chance we can have this in the cpp branch such that I can try this in Polly as well?

**Comment by skimo-openhub** [comment]
On Wed, Mar 07, 2018 at 06:50:26AM -0800, Tobias Grosser wrote:
> Very nice. Any chance we can have this in the cpp branch such that I can try this in Polly as well?

The purpose of this PR is to _remove_ stuff that is
only available in this repo, so it doesn't really
make sense on the cpp branch in mainline.

skimo

**Comment by tobig** [comment]
I understand that this PR by itself does not make sense. However, the first two patches that establish a list interface make sense in isl. Would be great to see them on public isl (together with the changes to export lists).

**Comment by skimo-openhub** [comment]
On Thu, Mar 08, 2018 at 04:05:22AM -0800, ftynse wrote:
> ftynse commented on this pull request.
> 
> What's the plan for iterator support?  Range-based `for` loops were an important usability for bindings, and it becomes even more important as we provide more functions for converting "implicit" collections (like map) as lists.

I'll add the 20 lines to TC.

skimo

**Comment by ftynse** [comment]
we start having a "isl-cpp-utilities" library that we should consider distributing together with isl or separately from TC

**Comment by tobig** [comment]
Yes, it would indeed be nice to make these isl-cpp-utilities part of the isl C++ bindings. Iterators were something we wanted to have in the C++ bindings since a long time.

**Pull request merged**
